### ISSUE TITLE
Restore and slow remove package index

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#4983]
I don't recall seeing a DeprecationWarning for this, thus it was a really big surprise to see the gazillion bug reports and failing CI run due to the removal of `package_index`. 
I do use it in some legacy infrastructure that is due to be refactored, yet I was fully expected to be on top of any sudden and user-affected breakages by being on top of the deprecations. Is there any chance to revert that part of the PR, too in favour of a more gentle removal following a deprecation period?

_Originally posted by @bsipocz in https://github.com/pypa/setuptools/pull/4963#issuecomment-2851940964_

**Comment by jaraco** [comment]
I was under the impression that package index was an internal implementation detail of easy install. This is the first I'm learning of this public use.

We could consider restoring it, especially if the impact is significant. Since you are possibly the only affected user, I'd like to consider other options.

How difficult would it be in your legacy services to pin to Setuptools<80?

**Comment by bsipocz** [comment]
The library is not legacy, but quite widely used, it's just its infrastructure that is dated. However, it was built with a now deprecated package template, so I expect other things are also using the same infrastructure (and indeed, there are quite a lot many finds on [github](https://github.com/search?q=%22from+setuptools.package_index+import+PackageIndex%22&type=code&p=2), though I expect most of these are obsolete). 

So while I fixed astroquery's `main`, I would still consider it to be a nice thing to make this removal a slower process, e.g. not breaking building from source for our last releases

**Comment by jaraco** [comment]
> Throwing a naive question: would it be hard to extract the code as a separate `setuptools.package_index` package ?

My guess is probably not, though I haven't looked into it. It probably would still have a dependency on Setuptools, which would mean the package would start out deprecated, but if someone wishes to do that as a temporary band-aid, I'd endorse it for the short term (order of months).

Since there hasn't been any response regarding the impact, I'm going to assume the impact is now negligible, so I'm closing this issue, but I can revisit it if anyone wishes to follow up with a compelling case.

**Comment by gotcha** [comment]
> It probably would still have a dependency on Setuptools, which would mean the package would start out deprecated...

@jaraco, Can you explain what you mean by "starting deprecated" ?

Did I miss anything outside https://packaging.python.org/en/latest/discussions/setup-py-deprecated/ ?

**Comment by jaraco** [comment]
> [@jaraco](https://github.com/jaraco), Can you explain what you mean by "starting deprecated" ?

Setuptools aims to be mainly a build backend, with the internal details of the library to be private details. I don't want downstream projects to develop a dependency on the implementation details of Setuptools (such as Distribution objects or the distutils commands behavior).

Perhaps "deprecated" was too strong a word - I'm not confident I've communicated this intended deprecation prominently enough. Regardless, it is the intent that I wanted to be clear about when considering a replacement.
