### ISSUE TITLE
namespace packages cannot be found by various tools.

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#83]
Originally reported by: **youngrok (Bitbucket: [youngrok](http://bitbucket.org/youngrok), GitHub: [youngrok](http://github.com/youngrok))**

---

All of these, `pkgutil.iter_modules`, `help(modules)`, `pydoc modules`, don't show namespace packages. IPython and eclipse pydev code completion doesn't work for namespace packages, either.

Of course importing namespace packages has no problem. It works. But supporting tools are also important. Current namespace package spec seems not so good.

It's because of absence of `__init__.py`. I know there are various reasons to skip `__init__.py` while installing namespace packages, but if it's not skipped, all problems will be fixed.

If we should respect PEP 420, `*-nspkg.pth` file should be fixed. Not just creating new module for namespace package, but registering all submodules of namespace packages is needed. 

I'm sorry if I've posted this issue on wrong place. I'm confusing I have to post this here or on PEP mailing list.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/83

**Comment by silkentrance** [comment]
@pganssle This might have been fixed by the fix for #97 in  #1312.

**Comment by silkentrance** [comment]
As for various tools not being able to resolve namespace packages, well, this is up to the tools, isn't it?

**Comment by pganssle** [comment]
@silkentrance I don't think #1312 actually fixes any existing *bugs*, all it does is provide a new API for people to create namespace packages.

`pkg_resources` is also provided by this repo, so if `pkg_resources.resource_filename` still doesn't understand PEP420 namespace packages, that's an ongoing problem.

**Comment by silkentrance** [comment]
@pganssle Ok, now I understand the issue, thanks for clearing this up.

**Comment by Avasam** [comment]
Note that setuptools no longer relies on `pkg_resources`, if this issue is still relevant, the symptoms will be different.

**Comment by abravalheri** [comment]
Thank you very much @Avasam, I agree. And we also have deprecated `pkg_resources.declare_namespace` a while ago, asking users to migrate to PEP 420.


I will close this issue as stale for now, but the author can re-open it with new information if necessary or create a new issue.
